# Generated by Django 4.2.10 on 2024-03-04 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubTasks',
            new_name='SubTask',
        ),
    ]
